### ISSUE TITLE
Command tic should be added to the code

### ISSUE THREAD

**Issue by wanyuac** [AlmaasLab/AutoKEGGRec#1]
An error arose when I ran ```outStruct = AutoKEGGRec("cbe", 'SingleRecs');```:

Error using toc
You must call TIC without an output argument before calling TOC without an input argument.

Error in AutoKEGGRec (line 268)
time = toc;

Adding a tic command before toc solves the problem.

**Comment by emikar** [comment]
Hey! We were unfortunately unable to reproduce the error with the provided bit of code. Could you give any further specifications that might help us reproduce it?

On line 77, there is a "tic" that should preclude the issue you seem to be encountering. If you could double-check that it's present, and see if the issue still occurs, that would be very helpful to us!

Thanks!
