### ISSUE TITLE
Cannot write SBML file

### ISSUE THREAD

**Issue by NatashaJorge** [AlmaasLab/AutoKEGGRec#2]
Hello! 

I'm trying to use AutoKEGGRec and I'm seeing an error with while writing SBML. My command is:

tic; 
outputStruct = AutoKEGGRec("eco", 'SingleRecs','ConsolidatedRec', ...
    'OmittedData','OrgRxnGen','DisconnectedReactions','GenePlot','Histogram', ...
    'writeSBML');
time=toc;

my error is:

Writing SBML files. This takes some time.
Writing ConsolidatedRec to file.
Each model.subSystems{x} has been changed to a character array.
Document written
Writing eco reconstruction to file.
Each model.subSystems{x} has been changed to a character array.
verifyModel: The following problems have been encountered in the model structure
propertiesNotMatched:
rules: Field does not match the required properties at the following positions:  

[then comes a list from 1 to 1280]

Error using writeCbModel (line 132)
The value of 'model' is invalid. It must satisfy the function:
@(x)verifyModel(model,'simpleCheck',true).

Error in AutoKEGGRec (line 1541)
            writeCbModel(singleStructs.(fieldNames{org}),'format',format,'fileName',[char(organismCodes(org)) 'Rec_' timeString]);

Please, how can I write the SBML file?

Thanks for your time and attention,
Best regards,
Natasha

**Comment by emikar** [comment]
Hi! Our sincerest apologies for missing your message. There were some issues with notifications stemming from a transfer of ownership of the repository, but we are catching up now. While it's unfortunate we could not fix the issue in a timely manner for you, we appreciate you letting us know about the issue so we can address it for other users!

**Comment by emikar** [comment]
The internal structures generated in the function were no longer up to date with that expected by the Cobra Toolbox. This has been fixed, and the function should now output SBML files correctly.
