### ISSUE TITLE
error about AutoKEGGRec

### ISSUE THREAD

**Issue by Chao-NNU** [AlmaasLab/AutoKEGGRec#3]
When I just run outputStruct=AutoKEGGRec("T00005"), an error happened, 
Error using containers.Map Empty keys are not allowed in this container.
Error in AutoKEGGRec (line 223)
rxnRef = containers.Map(rxnList,1:length(rxnList));

**Comment by tiffpong** [comment]
Hello, I am also running into the same error. Have you ever figured it out?

**Comment by Chao-NNU** [comment]
I still can not figure it out.

**Comment by niraito** [comment]
I get the same error 😞 I hope to see an update 🙏🏻

**Comment by CW1211** [comment]
Hello, I get the same error so I just wanted to check in to see if there is any update.

**Comment by emikar** [comment]
Hi! We are looking into the issue, and it seems there have been some updates to KEGG's API. We will be updating shortly.

Our apologies for the late response. There was some problems with ownership transfer of the repo and notifications; we have fixed this now, and hope to be more swift in addressing future issues!

**Comment by CW1211** [comment]
Hello, thank you for looking into the issue. Should it be working now? I just tried using it again and got the same error.

**Comment by emikar** [comment]
> Hello, thank you for looking into the issue. Should it be working now? I just tried using it again and got the same error.

Hey! The issue is now fixed. I also discovered we had missed another issue about writing to SBML, which we are currently working on. But getting the standard output structure for other kinds of analysis should now work! Thank you for your patience and interest in using our tool!
